### ISSUE TITLE
remove `fs-cp`?

### ISSUE THREAD

**Issue by tunnckoCore** [koajs/body-parsers#19]
Why it is there? Everyone can add it and use it directly, if he want it. This also blocks using this package in plugins, like 

``` js
var bodyParsers = require('koa-body-parsers')
var koa = require('koa')
var app = koa()

app.use(function * () {
  bodyParsers(this)
})
.use(function * () {
  this.body = yield this.request.json()
})
```

for example - i need it this way, because I'm going to use it in plugin that wraps these things.

Fails to set `.save` on `app.context`

```
TypeError: Cannot set property 'save' of undefined
      at /home/charlike/dev/final/koa-better-body/node_modules/koa-body-parsers/index.js:18:22
      at Array.forEach (native)
      at Function.module.exports.Object.keys.forEach.Object.keys.forEach.Object.keys.forEach (/home/charlike/dev/final/koa-better-body/node_modules/koa-body-parsers/index.js:17:24)
      at Object.plugin (/home/charlike/dev/final/koa-better-body/index.js:21:11)
      at next (native)
      at Object.<anonymous> (/home/charlike/dev/final/koa-better-body/node_modules/koa-compose/index.js:28:12)
      at next (native)
      at onFulfilled (/home/charlike/dev/final/koa-better-body/node_modules/co/index.js:65:19)
      at /home/charlike/dev/final/koa-better-body/node_modules/co/index.js:54:5
      at Object.co (/home/charlike/dev/final/koa-better-body/node_modules/co/index.js:50:10)
```

**Comment by jonathanong** [comment]
i don't mind. just needs to be a version bump

**Comment by tunnckoCore** [comment]
Great, want PR?

**Comment by tunnckoCore** [comment]
ping?

**Comment by coderhaoxin** [comment]
@tunnckoCore Submit a PR?
